# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-05-10 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='host_issue',
            old_name='team',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='team',
            new_name='project',
        ),
    ]
